### ISSUE TITLE
scx_wd40: Build failure on ARM due to missing `mempolicy`

### ISSUE THREAD

**Issue by EricccTaiwan** [sched-ext/scx#2474]
Hi, I recently encountered a build failure on ARM (`aarch64`) after rebasing to the latest commit.

```shell
$  uname -r
6.14.0-15-generic
$ lscpu 
Architecture:             aarch64
CPU(s):                   224
Model name:               ThunderX2-99xx
NUMA node(s):             2
```

Interestingly, the failing code involving `mempolicy` was introduced around 5 months ago, and I’m quite certain I was able to build successfully on ARM before the rebase.

The build now fails with errors like:
```c
error: no member named 'mempolicy' in 'struct task_struct'; did you mean 'policy'?
```

<details>
<summary>Full build log</summary>

```c
$ meson compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/underdog/eric/scx/build
ninja: Entering directory `/home/underdog/eric/scx/build'
[3/3] Generating rust_all with a custom command (wrapped by meson to set env)
FAILED: Cargo.toml.__PHONY__ 
/usr/bin/meson --internal exe --unpickle /home/underdog/eric/scx/build/meson-private/meson_exe_cargo_3733d421a119686c95c70b55b1a7acfef1777bdd.dat
while executing ['/home/underdog/.cargo/bin/cargo', 'build', '--manifest-path=../Cargo.toml', '--target-dir=.', '--quiet']
--- stdout ---

--- stderr ---
error: failed to run custom build command for `scx_wd40 v1.0.14 (/home/underdog/eric/scx/scheds/rust/scx_wd40)`

Caused by:
  process didn't exit successfully: `/home/underdog/eric/scx/build/./debug/build/scx_wd40-3194eabaf8eb44a9/build-script-build` (exit status: 101)
  --- stdout
  scx_utils:clang=ClangInfo { clang: "/usr/bin/clang", ver: "20.1.2", arch: "aarch64" } ["-g", "-O2", "-Wall", "-Wno-compare-distinct-pointer-types", "-D__TARGET_ARCH_arm64", "-mcpu=v3", "-mlittle-endian", "-idirafter", "/usr/lib/llvm-20/lib/clang/20/include", "-idirafter", "/usr/local/include", "-idirafter", "/usr/include/aarch64-linux-gnu", "-idirafter", "/usr/include", "-I/home/underdog/eric/scx/build/libbpf/src/usr/include", "-I/home/underdog/eric/scx/build/libbpf/include/uapi", "-I/home/underdog/eric/scx/build/./debug/build/scx_wd40-ea640ffde6e8e211/out/scx_utils-bpf_h/arch/arm64", "-I/home/underdog/eric/scx/build/./debug/build/scx_wd40-ea640ffde6e8e211/out/scx_utils-bpf_h", "-I/home/underdog/eric/scx/build/./debug/build/scx_wd40-ea640ffde6e8e211/out/scx_utils-bpf_h/bpf-compat"]

  --- stderr

  thread 'main' panicked at scheds/rust/scx_wd40/build.rs:24:10:
  called `Result::unwrap()` on an `Err` value: failed to build `src/bpf/placement.bpf.c`

  Caused by:
      0: failed to compile `src/bpf/placement.bpf.c`
      1: failed to compile /tmp/.tmpr4kTwE/placement.bpf.c from src/bpf/placement.bpf.c
      2: command `/usr/bin/clang -g -O2 -Wall -Wno-compare-distinct-pointer-types -D__TARGET_ARCH_arm64 -mcpu=v3 -mlittle-endian -idirafter /usr/lib/llvm-20/lib/clang/20/include -idirafter /usr/local/include -idirafter /usr/include/aarch64-linux-gnu -idirafter /usr/include -I/home/underdog/eric/scx/build/libbpf/src/usr/include -I/home/underdog/eric/scx/build/libbpf/include/uapi -I/home/underdog/eric/scx/build/./debug/build/scx_wd40-ea640ffde6e8e211/out/scx_utils-bpf_h/arch/arm64 -I/home/underdog/eric/scx/build/./debug/build/scx_wd40-ea640ffde6e8e211/out/scx_utils-bpf_h -I/home/underdog/eric/scx/build/./debug/build/scx_wd40-ea640ffde6e8e211/out/scx_utils-bpf_h/bpf-compat -I /tmp/.tmpICLld4/bpf/src -fno-stack-protector -g -O2 -target bpf -c src/bpf/placement.bpf.c -o /tmp/.tmpr4kTwE/placement.bpf.c` failed (exit status: 1)
      3: src/bpf/placement.bpf.c:60:55: error: no member named 'mempolicy' in 'struct task_struct'; did you mean 'policy'?
            60 |         if (!mempolicy_affinity || !bpf_core_field_exists(p->mempolicy) ||
               |                                                              ^~~~~~~~~
               |                                                              policy
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:188:49: note: expanded from macro 'bpf_core_field_exists'
           188 |         __builtin_preserve_field_info(___bpf_field_ref(field), BPF_FIELD_EXISTS)
               |                                                        ^
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:173:52: note: expanded from macro '___bpf_field_ref'
           173 |         ___bpf_apply(___bpf_field_ref, ___bpf_narg(args))(args)
               |                                                           ^
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:166:35: note: expanded from macro '___bpf_field_ref1'
           166 | #define ___bpf_field_ref1(field)        (field)
               |                                          ^
         /home/underdog/eric/scx/build/./debug/build/scx_wd40-ea640ffde6e8e211/out/scx_utils-bpf_h/arch/arm64/vmlinux.h:87372:15: note: 'policy' declared here
          87372 |         unsigned int policy;
                |                      ^
         src/bpf/placement.bpf.c:61:10: error: no member named 'mempolicy' in 'struct task_struct'; did you mean 'policy'?
            61 |             !p->mempolicy)
               |                 ^~~~~~~~~
               |                 policy
         /home/underdog/eric/scx/build/./debug/build/scx_wd40-ea640ffde6e8e211/out/scx_utils-bpf_h/arch/arm64/vmlinux.h:87372:15: note: 'policy' declared here
          87372 |         unsigned int policy;
                |                      ^
         src/bpf/placement.bpf.c:64:30: error: use of undeclared identifier 'MPOL_BIND'
            64 |         if (!(p->mempolicy->mode & (MPOL_BIND|MPOL_PREFERRED|MPOL_PREFERRED_MANY)))
               |                                     ^
         src/bpf/placement.bpf.c:64:40: error: use of undeclared identifier 'MPOL_PREFERRED'
            64 |         if (!(p->mempolicy->mode & (MPOL_BIND|MPOL_PREFERRED|MPOL_PREFERRED_MANY)))
               |                                               ^
         src/bpf/placement.bpf.c:64:55: error: use of undeclared identifier 'MPOL_PREFERRED_MANY'
            64 |         if (!(p->mempolicy->mode & (MPOL_BIND|MPOL_PREFERRED|MPOL_PREFERRED_MANY)))
               |                                                              ^
         src/bpf/placement.bpf.c:64:11: error: no member named 'mempolicy' in 'struct task_struct'
            64 |         if (!(p->mempolicy->mode & (MPOL_BIND|MPOL_PREFERRED|MPOL_PREFERRED_MANY)))
               |               ~  ^
         src/bpf/placement.bpf.c:73:14: error: no member named 'mempolicy' in 'struct task_struct'
            73 |         if ((int)p->mempolicy->home_node >= 0) {
               |                  ~  ^
         src/bpf/placement.bpf.c:75:26: error: no member named 'mempolicy' in 'struct task_struct'
            75 |                         node_dom_mask((u32)p->mempolicy->home_node);
               |                                            ~  ^
         src/bpf/placement.bpf.c:79:26: error: no member named 'mempolicy' in 'struct task_struct'
            79 |         mask = BPF_CORE_READ(p, mempolicy, nodes.bits);
               |                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:520:17: note: expanded from macro 'BPF_CORE_READ'
           520 |         ___type((src), a, ##__VA_ARGS__) __r;                               \
               |         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:391:38: note: expanded from macro '___type'
           391 | #define ___type(...) typeof(___arrow(__VA_ARGS__))
               |                             ~~~~~~~~~^~~~~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:389:64: note: expanded from macro '___arrow'
           389 | #define ___arrow(...) ___apply(___arrow, ___narg(__VA_ARGS__))(__VA_ARGS__)
               |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:381:31: note: expanded from macro '___arrow3'
           381 | #define ___arrow3(a, b, c) a->b->c
               |                            ~  ^
         src/bpf/placement.bpf.c:79:26: error: no member named 'mempolicy' in 'struct task_struct'; did you mean 'policy'?
            79 |         mask = BPF_CORE_READ(p, mempolicy, nodes.bits);
               |                                 ^~~~~~~~~
               |                                 policy
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:521:34: note: expanded from macro 'BPF_CORE_READ'
           521 |         BPF_CORE_READ_INTO(&__r, (src), a, ##__VA_ARGS__);                  \
               |                                         ^
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:429:20: note: expanded from macro 'BPF_CORE_READ_INTO'
           429 |                      dst, (src), a, ##__VA_ARGS__)                          \
               |                                  ^
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:420:18: note: expanded from macro '___core_read'
           420 |                                                       src, a, ##__VA_ARGS__)
               |                                                            ^
         note: (skipping 5 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:397:70: note: expanded from macro '___rd_first'
           397 | #define ___rd_first(fn, src, a) ___read(fn, &__t, ___type(src), src, a);
               |                                                                      ^
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:394:61: note: expanded from macro '___read'
           394 |         read_fn((void *)(dst), sizeof(*(dst)), &((src_type)(src))->accessor)
               |                                                                    ^
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:312:79: note: expanded from macro 'bpf_core_read'
           312 |         bpf_probe_read_kernel(dst, sz, (const void *)__builtin_preserve_access_index(src))
               |                                                                                      ^
         /home/underdog/eric/scx/build/./debug/build/scx_wd40-ea640ffde6e8e211/out/scx_utils-bpf_h/arch/arm64/vmlinux.h:87372:15: note: 'policy' declared here
          87372 |         unsigned int policy;
                |                      ^
         src/bpf/placement.bpf.c:79:26: error: no member named 'mempolicy' in 'struct task_struct'; did you mean 'policy'?
            79 |         mask = BPF_CORE_READ(p, mempolicy, nodes.bits);
               |                                 ^~~~~~~~~
               |                                 policy
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:521:34: note: expanded from macro 'BPF_CORE_READ'
           521 |         BPF_CORE_READ_INTO(&__r, (src), a, ##__VA_ARGS__);                  \
               |                                         ^
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:429:20: note: expanded from macro 'BPF_CORE_READ_INTO'
           429 |                      dst, (src), a, ##__VA_ARGS__)                          \
               |                                  ^
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:420:18: note: expanded from macro '___core_read'
           420 |                                                       src, a, ##__VA_ARGS__)
               |                                                            ^
         note: (skipping 5 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:380:28: note: expanded from macro '___arrow2'
           380 | #define ___arrow2(a, b) a->b
               |                            ^
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:394:44: note: expanded from macro '___read'
           394 |         read_fn((void *)(dst), sizeof(*(dst)), &((src_type)(src))->accessor)
               |                                                   ^
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:312:79: note: expanded from macro 'bpf_core_read'
           312 |         bpf_probe_read_kernel(dst, sz, (const void *)__builtin_preserve_access_index(src))
               |                                                                                      ^
         /home/underdog/eric/scx/build/./debug/build/scx_wd40-ea640ffde6e8e211/out/scx_utils-bpf_h/arch/arm64/vmlinux.h:87372:15: note: 'policy' declared here
          87372 |         unsigned int policy;
                |                      ^
         src/bpf/placement.bpf.c:79:9: warning: cast to smaller integer type 'typeof (((p))->policy)' (aka 'unsigned int') from 'const void *' [-Wvoid-pointer-to-int-cast]
            79 |         mask = BPF_CORE_READ(p, mempolicy, nodes.bits);
               |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:521:2: note: expanded from macro 'BPF_CORE_READ'
           521 |         BPF_CORE_READ_INTO(&__r, (src), a, ##__VA_ARGS__);                  \
               |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:428:2: note: expanded from macro 'BPF_CORE_READ_INTO'
           428 |         ___core_read(bpf_core_read, bpf_core_read,                          \
               |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           429 |                      dst, (src), a, ##__VA_ARGS__)                          \
               |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:419:2: note: expanded from macro '___core_read'
           419 |         ___apply(___core_read, ___empty(__VA_ARGS__))(fn, fn_ptr, dst,      \
               |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           420 |                                                       src, a, ##__VA_ARGS__)
               |                                                       ~~~~~~~~~~~~~~~~~~~~~~
         note: (skipping 3 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:416:2: note: expanded from macro '___core_readN'
           416 |         ___read(fn, dst, ___type(src, ___nolast(__VA_ARGS__)), __t,         \
               |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           417 |                 ___last(__VA_ARGS__));
               |                 ~~~~~~~~~~~~~~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:394:43: note: expanded from macro '___read'
           394 |         read_fn((void *)(dst), sizeof(*(dst)), &((src_type)(src))->accessor)
               |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:312:79: note: expanded from macro 'bpf_core_read'
           312 |         bpf_probe_read_kernel(dst, sz, (const void *)__builtin_preserve_access_index(src))
               |                                                                                      ^~~
         src/bpf/placement.bpf.c:79:37: error: member reference type 'typeof (((p))->policy)' (aka 'unsigned int') is not a pointer
            79 |         mask = BPF_CORE_READ(p, mempolicy, nodes.bits);
               |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:521:39: note: expanded from macro 'BPF_CORE_READ'
           521 |         BPF_CORE_READ_INTO(&__r, (src), a, ##__VA_ARGS__);                  \
               |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:429:25: note: expanded from macro 'BPF_CORE_READ_INTO'
           428 |         ___core_read(bpf_core_read, bpf_core_read,                          \
               |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           429 |                      dst, (src), a, ##__VA_ARGS__)                          \
               |                      ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:420:23: note: expanded from macro '___core_read'
           419 |         ___apply(___core_read, ___empty(__VA_ARGS__))(fn, fn_ptr, dst,      \
               |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           420 |                                                       src, a, ##__VA_ARGS__)
               |                                                       ~~~~~~~~~~^~~~~~~~~~~~
         note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:357:24: note: expanded from macro '___last2'
           357 | #define ___last2(a, x) x
               |                        ^
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:394:61: note: expanded from macro '___read'
           394 |         read_fn((void *)(dst), sizeof(*(dst)), &((src_type)(src))->accessor)
               |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
         /home/underdog/eric/scx/build/libbpf/src/usr/include/bpf/bpf_core_read.h:312:79: note: expanded from macro 'bpf_core_read'
           312 |         bpf_probe_read_kernel(dst, sz, (const void *)__builtin_preserve_access_index(src))
               |                                                                                      ^~~
         1 warning and 12 errors generated.
         
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

ninja: build stopped: subcommand failed.                                        
```

</details>

This happens in `placement.bpf.c`, where fields under `p->mempolicy` are accessed. Although there’s an early return with `bpf_core_field_exists(p->mempolicy)`, it seems the compiler still expands the macro and triggers the error during build time (only on ARM).

Any idea what might have changed recently that could have caused this? Thanks!

**Comment by EricccTaiwan** [comment]
Can someone please look into this issue? My ARM machine has been stuck ever since, and I still can't solve it. 😢

**Comment by Nudelsalad** [comment]
Hey @EricccTaiwan, I have experienced the same problem and looked into this issue: https://github.com/sched-ext/scx/issues/1320

For me, the fix was to fence the task_set_preferred_mempolicy_dom_mask function inside the scheds/rust/scx_wd40/src/bpf/placement.bpf.c file.

```c
#ifndef __TARGET_ARCH_arm64

/*
 * Sets the preferred domain mask according to the mempolicy. See man(2)
 * set_mempolicy for more details on mempolicy.
 */
static void task_set_preferred_mempolicy_dom_mask(struct task_struct *p,
						  task_ptr taskc)
{
	u32 node_id;
	u32 val = 0;
	void *mask;

	taskc->preferred_dom_mask = 0;

	if (!mempolicy_affinity || !bpf_core_field_exists(p->mempolicy) ||
	    !p->mempolicy)
		return;

	if (!(p->mempolicy->mode & (MPOL_BIND|MPOL_PREFERRED|MPOL_PREFERRED_MANY)))
		return;

	/*
	 * MPOL_BIND and MPOL_PREFERRED_MANY use the home_node field on the
	 * mempolicy struct, so use that for now. In the future the memory
	 * usage of the node can be checked to follow the same algorithm for
	 * where memory allocations will occur.
	 */
	if ((int)p->mempolicy->home_node >= 0) {
		taskc->preferred_dom_mask =
			node_dom_mask((u32)p->mempolicy->home_node);
		return;
	}

	mask = BPF_CORE_READ(p, mempolicy, nodes.bits);
	if (bpf_core_read(&val, sizeof(val), mask))
		return;

	bpf_for(node_id, 0, nr_nodes) {
		if (!(val & 1 << node_id))
			continue;

		taskc->preferred_dom_mask |= node_dom_mask(node_id);
	}

	return;
}

#else

static void task_set_preferred_mempolicy_dom_mask(struct task_struct *p,
                                                 task_ptr taskc)
{}

#endif
```
The purpose of this patch is to disable NUMA-aware memory locality optimizations on ARM64. This is necessary for hardware like the Raspberry Pi 5, which lacks NUMA support.

Hope this helps!

**Comment by EricccTaiwan** [comment]
> The purpose of this patch is to disable NUMA-aware memory locality optimizations on ARM64. This is necessary for hardware like the Raspberry Pi 5, which lacks NUMA support.
> 
> Hope this helps!

I think this change suppresses the warning for now, but I’m not sure what the impact of disabling NUMA-aware behavior would be. At least it allows me to build successfully for now.
